### ISSUE TITLE
Add an empty state for custom category

### ISSUE THREAD

**Issue by rc-young** [willowtreeapps/eyespeak-ios#337] opened 2020-05-08 15:56 UTC
**As a vocable app user, I would like to see an empty state message when I have just added a category**

**Acceptance Criteria**
- user navigates to the categories section of the app
- Add a new category by tapping on the + option
- After successfully adding a category, navigating to the category on the home screen show display a empty state screen.

**Comment by SashankPatel** [comment] 2022-03-09 15:56
Closing this out.  It is a duplicate of 253.

**Closed as completed by SashankPatel** 2022-03-09 15:56 UTC
Labels: v1.4, Custom Categories
