### ISSUE TITLE
Add Element Identifier Strings File

### ISSUE THREAD

**Issue by rhsalas3** [willowtreeapps/eyespeak-ios#475] opened 2022-03-16 15:36 UTC
For automation identifiers it may be useful to create a .strings file that we can use to reference identifiers from, instead of hard coding each string in various locations.

For example, each screen with the back button would have a line of code similar to `backButton.accessibilityIdentifier = "navigationBar.backButton"`. We could instead use a .strings file to reference the same identifier -> `backButton.accessibilityIdentifier = NSLocalizedString("backButton")`. This would make it easier to change the identifier, prevent issues with typos, etc.

**Acceptance Criteria**:
- Element accessibility (a11y) identifiers are maintained in a .strings file
- Existing a11y identifiers are refactored to reference their id from the file/class

**Comment by rhsalas3** [comment] 2022-03-16 15:41
@SashankPatel 

While implementing code changes from some PR feedback I thought that this would be something good to have, in order to maintain identifiers used for automation. 

Maybe we can discuss this ticket sometime, as a team. Otherwise, it's definitely a "nice to have" thing and not a high priority.

Putting it in the Backlog column.

CC: @Clstroud @jsmorgan42

**Comment by rowildcard** [comment] 2022-06-21 16:57
This is a duplicate of 690.

**Closed as completed by rowildcard** 2022-06-21 16:57 UTC
Labels: Enhancement, question, automation, Nice To Have
